
version: "3.7"
services:
    mongodb:
        container_name: app-mongo-database
        image: mongo
        environment:
        - MONGO_INITDB_DATABASE="userhobbies"
        ports:
        - "27017:27017"
        networks:
            app-network:
                ipv4_address: 172.27.0.21
                aliases:
                - mongodb.net.local
    backend:
        container_name: app-backend
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
        - "2022:2022"
        links:
            - mongodb
        environment:
            - MONGODB_URL='mongodb://172.27.0.21:27017/userhobbies'
        networks:
            app-network:
                ipv4_address: 172.27.0.22
                aliases:
                - app-backend.local

networks:
    app-network:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16